#!/usr/bin/env bash 

# ========================================================================
# Copyright (c) 2021 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.argenv.sh

EXECUTABLE="`basename $0`"
BUNDLE_PRODUCT_LIST="gemfire geode hazelcast jet snappydata coherence"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Generate all catalog files

SYNOPSIS
   $EXECUTABLE 

DESCRIPTION
   Generates all catalog files

DEFAULT
   $EXECUTABLE

EOF
   exit
fi

PRODUCT_LIST="none geode hazelcast jet snappydata coherence"
ALL_MD="all-catalog.md"

for PRODUCT in $PRODUCT_LIST; do
  echo "Generating $PRODUCT..."
  ./update_catalog -header -product $PRODUCT
done

NONE_HEADER="[Generice (none) Catalog](#books-none-bundle-catalog---use-cases-books)"
GEODE_HEADER="[Geode/GemFireBundle Catalog](#books-geodegemfire-bundle-catalog---use-cases-books)"
HAZELCAST_HEADER="[Hazelcast IMDG Bundle Catalog](#books-hazelcast-imdg-bundle-catalog---use-cases-books)"
JET_HEADER="[Hazelcast Jet Bundle Catalog](#books-hazelcast-jet-bundle-catalog---use-cases-books)"
SNAPPYDATA_HEADER="[SnappyData/ComputeDB Bundle Catalog](#books-snappydataconputedb-bundle-catalog---use-cases-books)"
COHERENCE_HEADER="[Coherence Bundle Catalog](#books-coherence-bundle-catalog---use-cases-books)"

# Generate combined catalog
echo "Generating combined catalog..."
echo "# :earth_americas: PadoGrid Combined Bundle Catalog - Use Cases :earth_americas:" > $ALL_MD
echo "" >> $ALL_MD
echo "This catalog combines all the online PadoGrid bundles. The bundles in each data grid product are grouped as follows." >> $ALL_MD
echo "" >> $ALL_MD
echo "- $NONE_HEADER" >> $ALL_MD
echo "- $GEODE_HEADER" >> $ALL_MD
echo "- $HAZELCAST_HEADER" >> $ALL_MD
echo "- $JET_HEADER" >> $ALL_MD
echo "- $SNAPPYDATA_HEADER" >> $ALL_MD
echo "- $COHERENCE_HEADER" >> $ALL_MD
for PRODUCT in $PRODUCT_LIST; do
    echo "" >> $ALL_MD
    echo "---" >> $ALL_MD
    echo "" >> $ALL_MD
    cat $PRODUCT-catalog.md >> $ALL_MD
done
