#!/usr/bin/env bash 

# ========================================================================
# Copyright (c) 2021 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.argenv.sh

EXECUTABLE="`basename $0`"
BUNDLE_PRODUCT_LIST="gemfire geode hazelcast jet snappydata coherence"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Generate all catalog files

SYNOPSIS
   $EXECUTABLE 

DESCRIPTION
   Generates all catalog files

DEFAULT
   $EXECUTABLE

EOF
   exit
fi

PRODUCT_LIST="geode hazelcast snappydata coherence"
ALL_MD="build/all-catalog.md"

for PRODUCT in $PRODUCT_LIST; do
  echo "Generating $PRODUCT..."
  ./update_catalog -header -product $PRODUCT
done

# Generate combined catalog
echo "Generating combined catalog..."
echo "# :earth_americas: Combined Catalog - Use Cases :earth_americas:" > $ALL_MD
echo "" >> $ALL_MD
echo "This catalog combines all the online PadoGrid bundles." >> $ALL_MD
echo "" >> $ALL_MD
echo "The online bundles can be installed by executing the \`install_bundle\` commands as shown below. To view use case details for each bundle, click on their image." >> $ALL_MD
for PRODUCT in $PRODUCT_LIST; do
    echo "" >> $ALL_MD
    echo "---" >> $ALL_MD
    echo "" >> $ALL_MD
    cat $PRODUCT-catalog.md >> $ALL_MD
done
