#!/usr/bin/env bash 

# ========================================================================
# Copyright (c) 2021 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.argenv.sh

EXECUTABLE="`basename $0`"
BUNDLE_PRODUCT_LIST="gemfire geode hazelcast jet snappydata coherence"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Generate all catalog files

SYNOPSIS
   $EXECUTABLE 

DESCRIPTION
   Generates all catalog files

DEFAULT
   $EXECUTABLE

EOF
   exit
fi

PRODUCT_LIST="none geode hazelcast jet snappydata coherence"
ALL_MD="all-catalog.md"

for PRODUCT in $PRODUCT_LIST; do
  echo "Generating $PRODUCT..."
  ./update_catalog -header -product $PRODUCT
done

LINK_HEADER="![PadoGrid](https://github.com/padogrid/padogrid/raw/develop/images/padogrid-3d-16x16.png) [*PadoGrid*](https://github.com/padogrid) | [*Catalogs*](https://github.com/padogrid/catalog-bundles/blob/master/all-catalog.md) | [*Manual*](https://github.com/padogrid/padogrid/wiki) | [*FAQ*](https://github.com/padogrid/padogrid/wiki/faq) | [*Releases*](https://github.com/padogrid/padogrid/releases) | [*Templates*](https://github.com/padogrid/padogrid/wiki/Using-Bundle-Templates) | [*Pods*](https://github.com/padogrid/padogrid/wiki/Understanding-Padogrid-Pods) | [*Kubernetes*](https://github.com/padogrid/padogrid/wiki/Kubernetes) | [*Docker*](https://github.com/padogrid/padogrid/wiki/Docker) | [*Apps*](https://github.com/padogrid/padogrid/wiki/Apps) | [*Quick Start*](https://github.com/padogrid/padogrid/wiki/Quick-Start)"

NONE_HEADER="[Generic (none) Catalog](#books-generic-none-bundle-catalog-books)"
GEODE_HEADER="[Geode/GemFire Catalog](#books-geodegemfire-bundle-catalog-books)"
HAZELCAST_HEADER="[Hazelcast IMDG Catalog](#books-hazelcast-imdg-bundle-catalog-books)"
JET_HEADER="[Hazelcast Jet Catalog](#books-hazelcast-jet-bundle-catalog-books)"
SNAPPYDATA_HEADER="[SnappyData/ComputeDB Catalog](#books-snappydataconputedb-bundle-catalog-books)"
COHERENCE_HEADER="[Coherence Catalog](#books-coherence-bundle-catalog-books)"

# Generate combined catalog
echo "Generating combined catalog..."

# Start with the link header
echo "$LINK_HEADER" > $ALL_MD
echo "" >> $ALL_MD
echo "---" >> $ALL_MD
echo "" >> $ALL_MD
echo "# :earth_americas: PadoGrid Bundle Catalogs :earth_americas:" >> $ALL_MD
echo "" >> $ALL_MD
echo "*Bundles represent fully implemented use cases.* This page lists all of the open source PadoGrid bundles. The bundles in each product are grouped as follows." >> $ALL_MD
echo "" >> $ALL_MD
echo "- $NONE_HEADER" >> $ALL_MD
echo "- $GEODE_HEADER" >> $ALL_MD
echo "- $HAZELCAST_HEADER" >> $ALL_MD
echo "- $JET_HEADER" >> $ALL_MD
echo "- $SNAPPYDATA_HEADER" >> $ALL_MD
echo "- $COHERENCE_HEADER" >> $ALL_MD

# Create link header files for products
LINK_HEADER_TOP_FILE="tmp/top_link.md"
echo "$LINK_HEADER" > $LINK_HEADER_TOP_FILE
echo "" >> "$LINK_HEADER_TOP_FILE"
echo "---" >> "$LINK_HEADER_TOP_FILE"
echo "" >> "$LINK_HEADER_TOP_FILE"
LINK_HEADER_BOTTOM_FILE="tmp/bottom_link.md"
echo "" > "$LINK_HEADER_BOTTOM_FILE"
echo "---" >> "$LINK_HEADER_BOTTOM_FILE"
echo "" >> "$LINK_HEADER_BOTTOM_FILE"
echo "$LINK_HEADER" >> "$LINK_HEADER_BOTTOM_FILE"

# Append prodct MDs
for PRODUCT in $PRODUCT_LIST; do
    echo "" >> $ALL_MD
    echo "---" >> $ALL_MD
    echo "" >> $ALL_MD
    cat $PRODUCT-catalog.md >> $ALL_MD

    # Add the link hader in the product catalog md
    # Top
    mv $PRODUCT-catalog.md tmp/tmp.md
    cp $LINK_HEADER_TOP_FILE $PRODUCT-catalog.md
    cat tmp/tmp.md >> $PRODUCT-catalog.md
    # Bottom
    cat $LINK_HEADER_BOTTOM_FILE >> $PRODUCT-catalog.md
done

# End with the link header
echo "" >> $ALL_MD
echo "---" >> $ALL_MD
echo "" >> $ALL_MD
echo "$LINK_HEADER" >> $ALL_MD

echo "$EXECUTABLE complete."
